version: '3.3'
services:
  nodeapi:
    build:
      context: ./node-apis-service
      dockerfile: Dockerfile
    restart: always
    # docker run -t is allow
    tty: true
    # application port, this is take value from env file
    ports:
      - 3000:3000
    networks:
      - network1

  pythonapi:
    build:
      context: ./python-apis-service
      dockerfile: Dockerfile
    restart: always
    # docker run -t is allow
    tty: true
    # application port, this is take value from env file
    ports:
      - 4000:4000
    networks:
      - network1
  
#Docker Networks
networks:
  # All container connect in a network
  network1:
    driver: bridge


    